[project]
name = "datachef"

[[resources]]
name = "db"
type = "postgres"
version = "16"
connection = "asyncpg"

[[resources]]
name = "redis"
type = "redis"

[[processes]]
name = "api"
type = "web"
path = "api"
port = 8000
public_host = "api-datachef.paastech.izoret.fr"

[[processes]]
name = "worker"
type = "worker"
path = "worker"

[[processes]]
name = "frontend"
type = "web"
path = "frontend"
port = 3000
public_host = "front-datachef.paastech.izoret.fr"
build_env = { VITE_API_URL = "https://api-datachef.paastech.izoret.fr" }